# Generated by Django 4.1.1 on 2022-09-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=40)),
                ('entrenador', models.CharField(max_length=40)),
                ('fundacion', models.DateField()),
                ('apodo', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Futbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=40)),
                ('entrenador', models.CharField(max_length=40)),
                ('fundacion', models.DateField()),
                ('apodo', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=40)),
                ('altura', models.CharField(max_length=40)),
                ('nacimiento', models.DateField()),
                ('apodo', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=40)),
            ],
        ),
    ]
